import type { Metadata } from 'next';
import HeaderLounge from '@/components/headers/Lounge';
import Footer from '@/components/footers/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HeaderLounge />
      {children}
      <Footer />
    </>
  );
}
