import type { Metadata } from 'next';
import HeaderSettings from '@/components/headers/Settings';
// import '../globals.sass';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HeaderSettings />
      {children}
    </>
  );
}
