import type { Metadata } from 'next';
import localFont from 'next/font/local';
// import '../globals.sass';

const Pre = localFont({
  src: '../fonts/PretendardVariable.woff2',
  style: 'normal',
  variable: '--square',
});

const Square = localFont({
  src: '../fonts/NanumSquareNeoVF.woff2',
  style: 'normal',
  variable: '--square',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-KR" className={`${Pre.variable} ${Square.variable}`}>
      <body>{children}</body>
    </html>
  );
}
