import { ReactNode } from 'react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Noto_Sans_KR, Noto_Serif_KR, Hahmlet } from 'next/font/google';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import ThemeProviderClient from './themeProvider';
import { getSessionClaims } from '@/lib/session';
import AuthStateProvider from '@/components/auth/AuthStateProvider';
import Verify2fa from '@/components/auth/Verify2fa';
import { LoadingIndicator } from '@/components/LoadingIndicator';
import './globals.sass';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Sans = Noto_Sans_KR({
  subsets: ['cyrillic'],
  variable: '--sans',
});

const Serif = Noto_Serif_KR({
  subsets: ['cyrillic'],
  variable: '--serif',
});

const Ham = Hahmlet({
  subsets: ['latin'],
  variable: '--ham',
});

const Pre = localFont({
  src: './fonts/PretendardVariable.woff2',
  style: 'normal',
  variable: '--pre',
});

const Neo = localFont({
  src: './fonts/NanumSquareNeoVF.woff2',
  style: 'normal',
  variable: '--neo',
});

export default async function RootLayout({ children }: { children: ReactNode }) {
  const sessionClaims = await getSessionClaims();
  const needsTotp =
    sessionClaims?.userId && sessionClaims?.authenticationLevel === 'aal1' && sessionClaims?.hasTotp === true;
  return (
    <html lang="ko-KR" className={`${Pre.variable} ${Neo.variable} ${Sans.variable} ${Serif.variable} ${Ham.variable}`}>
      <body>
        <div id="__app">
          <AuthStateProvider>
            <AppRouterCacheProvider>
              <ThemeProviderClient>
                {needsTotp ? (
                  <>
                    <Verify2fa />
                    <main>
                      <div className="container">
                        <div
                          className="content"
                          style={{ display: 'flex', alignItems: 'center', justifyContent: 'center' }}
                        >
                          <LoadingIndicator />
                        </div>
                      </div>
                    </main>
                  </>
                ) : (
                  children
                )}
              </ThemeProviderClient>
            </AppRouterCacheProvider>
          </AuthStateProvider>
        </div>
      </body>
    </html>
  );
}
