import { ReactNode } from 'react';
import type { Metadata } from 'next';
import './globals.sass';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return children;
}
