import { ReactNode } from 'react';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import ThemeProviderClient from './themeProvider';
// import './globals.sass';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const Pre = localFont({
  src: './fonts/PretendardVariable.woff2',
  style: 'normal',
  variable: '--square',
});

const Square = localFont({
  src: './fonts/NanumSquareNeoVF.woff2',
  style: 'normal',
  variable: '--square',
});

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ko-KR" className={`${Pre.variable} ${Square.variable}`}>
      <body>
        <AppRouterCacheProvider>
          <ThemeProviderClient>{children}</ThemeProviderClient>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
