import type { Metadata } from 'next';
import HeaderHub from '@/components/headers/Hub';
import Footer from '@/components/footers/Footer';
// import '../globals.sass';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HeaderHub />
      {children}
      <Footer />
    </>
  );
}
