import type { Metadata } from 'next';
import HeaderSite from '@/components/headers/Site';
import FooterSite from '@/components/footers/Site';
// import '../globals.sass';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HeaderSite />
      {children}
      <FooterSite />
    </>
  );
}
