import type { Metadata } from 'next';
import HeaderSiteGuard from './[siteName]/headerSiteGuard';
// import '../globals.sass';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HeaderSiteGuard />
      {children}
    </>
  );
}
